Fixes to support multiple namespaces
google/kctf pull request #185
Opened 2021-01-12 16:41 UTC by sroettger

We don't specify the namespace in various commands. Fix that by reading it with yq and then using the namespace everywhere we run kubectl.

2021-01-12 21:09 UTC, sirdarckcat requested changes

2021-01-12 21:09 UTC, sirdarckcat commented on dist/activate
> +      CHALLENGE_NAMESPACE=$("${KCTF_BIN}/yq" eval --exit-status '.metadata.name' "${current_dir}/challenge.yaml" 2>/dev/null)
.namespace?

2021-01-13 10:15 UTC, sroettger commented on dist/activate
> +      CHALLENGE_NAMESPACE=$("${KCTF_BIN}/yq" eval --exit-status '.metadata.name' "${current_dir}/challenge.yaml" 2>/dev/null)
done

2021-01-13 12:40 UTC, sirdarckcat approved these changes

2021-01-13 12:40 UTC, merged